"""
The contact/support ticket system — deliberately NOT organization-scoped
like almost everything else in this codebase. A ticket can be submitted
by anyone on the public marketing site, including people who have never
created a CanoryAI account at all, so there's no `organization_id` or
`user_id` to hang RLS off of the way the rest of the schema does.

Access control for this feature is enforced in application code, not
Postgres RLS policies — see the migration for why RLS isn't the right
tool here, and app/api/v1/contact.py for how ticket ownership is
verified (ticket number + the email it was created with) instead.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base

TICKET_STATUSES = ("open", "in_progress", "resolved", "closed")
MESSAGE_SENDER_TYPES = ("customer", "admin")


class ContactTicket(Base):
    __tablename__ = "contact_tickets"
    __table_args__ = (
        CheckConstraint(f"status IN {TICKET_STATUSES}", name="ck_contact_tickets_valid_status"),
        Index("ix_contact_tickets_email", "email"),
        {
            "comment": (
                "Public contact/support tickets — not organization-scoped. "
                "Access control is application-level (ticket number + email), not RLS."
            )
        },
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid()
    )
    # Human-readable, e.g. "CNRY-1042" — generated by a Postgres sequence
    # in the migration, not application code, so it's guaranteed unique
    # and gap-free even under concurrent submissions.
    ticket_number: Mapped[str] = mapped_column(String(20), nullable=False, unique=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    email: Mapped[str] = mapped_column(String(255), nullable=False)
    company: Mapped[str | None] = mapped_column(String(255), nullable=True)
    subject: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, server_default="open")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )


class ContactTicketMessage(Base):
    __tablename__ = "contact_ticket_messages"
    __table_args__ = (
        CheckConstraint(f"sender_type IN {MESSAGE_SENDER_TYPES}", name="ck_contact_ticket_messages_valid_sender"),
        Index("ix_contact_ticket_messages_ticket_id", "ticket_id"),
        {"comment": "Message thread for a contact_tickets row — the original message is the first row."},
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid()
    )
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("contact_tickets.id", ondelete="CASCADE"), nullable=False
    )
    sender_type: Mapped[str] = mapped_column(String(10), nullable=False)
    sender_name: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())
