"""add shipment payload column

Revision ID: 171f934ce79c
Revises: 35ced8187ab8
Create Date: 2026-07-08 01:50:07.774905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '171f934ce79c'
down_revision: Union[str, Sequence[str], None] = '35ced8187ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'payload')
    # ### end Alembic commands ###
