"""add shipment compliance summary columns

Revision ID: 35ced8187ab8
Revises: 92bc9aeb4493
Create Date: 2026-07-07 16:04:17.228552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ced8187ab8'
down_revision: Union[str, Sequence[str], None] = '92bc9aeb4493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'organization_id',
               existing_type=sa.UUID(),
               comment='The tenant this event belongs to. Enforced by RLS — see the multi-tenancy migration.',
               existing_comment='The tenant this event belongs to. Enforced by RLS — see this migration.',
               existing_nullable=False)
    op.alter_column('audit_log', 'shipment_id',
               existing_type=sa.UUID(),
               comment='Links this event to a shipment. Not a foreign key to `shipments.id` for historical reasons (this column predates the shipments table); tenant isolation for this table is enforced via organization_id directly, not via a join, so this remains safe.',
               existing_comment='Links this event to a shipment. Not a foreign key: shipments are not yet a persisted table (see app/services/shipment_store.py) — this column is indexed for query performance and will become a real foreign key once a shipments table exists.',
               existing_nullable=False)
    op.create_table_comment(
        'audit_log',
        'APPEND-ONLY legal evidence ledger for EUDR compliance actions. INSERT only — never UPDATE or DELETE. Enforced by a database trigger and role permissions; see the audit_log migration.',
        existing_comment='APPEND-ONLY legal evidence ledger for EUDR compliance actions. INSERT only — never UPDATE or DELETE. Enforced by a database trigger and role permissions; see this migration file.',
        schema=None
    )
    op.add_column('shipments', sa.Column('documents_processed', sa.Integer(), nullable=True))
    op.add_column('shipments', sa.Column('average_confidence', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('critical_farms', sa.Integer(), nullable=True))
    op.add_column('shipments', sa.Column('verified_farms', sa.Integer(), nullable=True))
    op.add_column('shipments', sa.Column('pending_verification', sa.Integer(), nullable=True))
    op.add_column('shipments', sa.Column('mass_balance_status', sa.String(length=50), nullable=True))
    op.add_column('shipments', sa.Column('commodity', sa.String(length=255), nullable=True))
    op.add_column('shipments', sa.Column('country_of_production', sa.String(length=255), nullable=True))
    op.create_index('ix_shipments_organization_id_created_at', 'shipments', ['organization_id', 'created_at'], unique=False)
    op.create_table_comment(
        'shipments',
        'Organization-scoped ownership ledger + compliance summary for processed shipments. The full per-document extraction payload lives in the in-memory shipment store (see app/services/shipment_store.py) — this row is the durable, RLS-protected record of which organization/user a shipment belongs to, plus enough summary data to list and aggregate shipments without depending on that cache.',
        existing_comment='Organization-scoped ownership ledger for processed shipments. The full extraction/compliance payload lives in the in-memory shipment store (see app/services/shipment_store.py) — this row is the durable, RLS-protected record of which organization and user a shipment belongs to.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'shipments',
        'Organization-scoped ownership ledger for processed shipments. The full extraction/compliance payload lives in the in-memory shipment store (see app/services/shipment_store.py) — this row is the durable, RLS-protected record of which organization and user a shipment belongs to.',
        existing_comment='Organization-scoped ownership ledger + compliance summary for processed shipments. The full per-document extraction payload lives in the in-memory shipment store (see app/services/shipment_store.py) — this row is the durable, RLS-protected record of which organization/user a shipment belongs to, plus enough summary data to list and aggregate shipments without depending on that cache.',
        schema=None
    )
    op.drop_index('ix_shipments_organization_id_created_at', table_name='shipments')
    op.drop_column('shipments', 'country_of_production')
    op.drop_column('shipments', 'commodity')
    op.drop_column('shipments', 'mass_balance_status')
    op.drop_column('shipments', 'pending_verification')
    op.drop_column('shipments', 'verified_farms')
    op.drop_column('shipments', 'critical_farms')
    op.drop_column('shipments', 'average_confidence')
    op.drop_column('shipments', 'documents_processed')
    op.create_table_comment(
        'audit_log',
        'APPEND-ONLY legal evidence ledger for EUDR compliance actions. INSERT only — never UPDATE or DELETE. Enforced by a database trigger and role permissions; see this migration file.',
        existing_comment='APPEND-ONLY legal evidence ledger for EUDR compliance actions. INSERT only — never UPDATE or DELETE. Enforced by a database trigger and role permissions; see the audit_log migration.',
        schema=None
    )
    op.alter_column('audit_log', 'shipment_id',
               existing_type=sa.UUID(),
               comment='Links this event to a shipment. Not a foreign key: shipments are not yet a persisted table (see app/services/shipment_store.py) — this column is indexed for query performance and will become a real foreign key once a shipments table exists.',
               existing_comment='Links this event to a shipment. Not a foreign key to `shipments.id` for historical reasons (this column predates the shipments table); tenant isolation for this table is enforced via organization_id directly, not via a join, so this remains safe.',
               existing_nullable=False)
    op.alter_column('audit_log', 'organization_id',
               existing_type=sa.UUID(),
               comment='The tenant this event belongs to. Enforced by RLS — see this migration.',
               existing_comment='The tenant this event belongs to. Enforced by RLS — see the multi-tenancy migration.',
               existing_nullable=False)
    # ### end Alembic commands ###
