"""add contact ticket system

Revision ID: 48f542bac65b
Revises: 4b58fa9baf05
Create Date: 2026-07-11 04:45:25.398320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f542bac65b'
down_revision: Union[str, Sequence[str], None] = '4b58fa9baf05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A real Postgres sequence, not application-generated numbering — this
    # guarantees uniqueness and gap-free ordering under concurrent
    # ticket submissions without needing a SELECT-then-INSERT race
    # condition anywhere in application code.
    op.execute("CREATE SEQUENCE contact_ticket_number_seq START 1000;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'resolved', 'closed')", name='ck_contact_tickets_valid_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number'),
    comment='Public contact/support tickets — not organization-scoped. Access control is application-level (ticket number + email), not RLS.'
    )
    op.create_index('ix_contact_tickets_email', 'contact_tickets', ['email'], unique=False)
    op.execute(
        "ALTER TABLE contact_tickets ALTER COLUMN ticket_number "
        "SET DEFAULT ('CNRY-' || nextval('contact_ticket_number_seq')::text);"
    )

    op.create_table('contact_ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sender_type IN ('customer', 'admin')", name='ck_contact_ticket_messages_valid_sender'),
    sa.ForeignKeyConstraint(['ticket_id'], ['contact_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Message thread for a contact_tickets row — the original message is the first row.'
    )
    op.create_index('ix_contact_ticket_messages_ticket_id', 'contact_ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###

    # No RLS on these two tables, deliberately — every other table in
    # this codebase is organization-scoped and RLS is the right tool for
    # that. Tickets aren't: they're created by people who may have no
    # CanoryAI account or organization at all, and "ownership" is
    # verified by ticket number + submitting email in application code
    # (see app/api/v1/contact.py), not a JWT's organization_id claim RLS
    # could check. Instead, access is restricted the more basic way —
    # only canopyai_app (the main backend, which enforces the
    # ticket-number+email check itself) and service_role (the separate
    # admin panel, for staff) can touch these tables at all; anon and
    # authenticated (a raw Supabase client from a browser) get no grant
    # and therefore no access, the same practical effect as RLS blocking
    # them, without forcing a row-level-security policy onto data that
    # isn't shaped for one.
    op.execute("GRANT SELECT, INSERT, UPDATE ON contact_tickets TO canopyai_app;")
    op.execute("GRANT SELECT, INSERT ON contact_ticket_messages TO canopyai_app;")
    op.execute("GRANT USAGE ON SEQUENCE contact_ticket_number_seq TO canopyai_app;")
    op.execute("GRANT SELECT, INSERT, UPDATE ON contact_tickets TO service_role;")
    op.execute("GRANT SELECT, INSERT ON contact_ticket_messages TO service_role;")
    op.execute("GRANT USAGE ON SEQUENCE contact_ticket_number_seq TO service_role;")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_ticket_messages_ticket_id', table_name='contact_ticket_messages')
    op.drop_table('contact_ticket_messages')
    op.drop_index('ix_contact_tickets_email', table_name='contact_tickets')
    op.drop_table('contact_tickets')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS contact_ticket_number_seq;")
