"""add export approval gate

Revision ID: 4b58fa9baf05
Revises: 327c7eef5733
Create Date: 2026-07-10 18:14:42.308100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b58fa9baf05'
down_revision: Union[str, Sequence[str], None] = '327c7eef5733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Explicit compliance sign-off gating XML export when Organization.require_export_approval is true.'
    )
    op.create_index('ix_shipment_approvals_organization_id', 'shipment_approvals', ['organization_id'], unique=False)
    op.create_index('ix_shipment_approvals_shipment_id', 'shipment_approvals', ['shipment_id'], unique=False)
    op.add_column('organizations', sa.Column('require_export_approval', sa.Boolean(), server_default='true', nullable=False))

    op.execute("ALTER TABLE shipment_approvals ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE shipment_approvals FORCE ROW LEVEL SECURITY;")
    op.execute(
        """
        CREATE POLICY shipment_approvals_own_org ON shipment_approvals
        FOR ALL USING (organization_id = get_user_organization_id())
        WITH CHECK (organization_id = get_user_organization_id());
        """
    )
    op.execute("GRANT SELECT, INSERT ON shipment_approvals TO canopyai_app;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS shipment_approvals_own_org ON shipment_approvals;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'require_export_approval')
    op.drop_index('ix_shipment_approvals_shipment_id', table_name='shipment_approvals')
    op.drop_index('ix_shipment_approvals_organization_id', table_name='shipment_approvals')
    op.drop_table('shipment_approvals')
    # ### end Alembic commands ###
