"""add raw_documents storage_path column

Revision ID: 4d2e09507c82
Revises: a60279514030
Create Date: 2026-07-09 00:56:58.596040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2e09507c82'
down_revision: Union[str, Sequence[str], None] = 'a60279514030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_documents', sa.Column('storage_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_documents', 'storage_path')
    # ### end Alembic commands ###
