"""add notifications table

Revision ID: 690ce11f4fef
Revises: 60ec838e8b1c
Create Date: 2026-07-10 07:34:52.341568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690ce11f4fef'
down_revision: Union[str, Sequence[str], None] = '60ec838e8b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('shipment_completed', 'shipment_failed', 'team_member_added', 'team_member_removed', 'plan_changed', 'quota_warning', 'webhook_failed')", name='ck_notifications_valid_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment="In-app notifications. user_id NULL means 'visible to every member of the organization' (e.g. a plan change); a specific user_id means it's for them alone."
    )
    op.create_index('ix_notifications_organization_id', 'notifications', ['organization_id'], unique=False)
    op.create_index('ix_notifications_recipient_unread', 'notifications', ['organization_id', 'user_id', 'read_at'], unique=False)

    # RLS: a member sees notifications addressed to them personally, OR
    # addressed to the whole org (user_id IS NULL) — but only within
    # their own organization either way. INSERT/UPDATE are both scoped
    # to "own org" too: INSERT so the backend's own writes (via a
    # service session, same pattern as audit logging) stay org-scoped
    # like everything else; UPDATE specifically so "mark as read" only
    # ever touches the caller's own organization's rows, never another
    # tenant's.
    op.execute("ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE notifications FORCE ROW LEVEL SECURITY;")

    op.execute(
        """
        CREATE POLICY notifications_select_own_org ON notifications
        FOR SELECT USING (
            organization_id = get_user_organization_id()
            AND (user_id IS NULL OR user_id = auth.uid())
        );
        """
    )
    op.execute(
        """
        CREATE POLICY notifications_insert_own_org ON notifications
        FOR INSERT WITH CHECK (organization_id = get_user_organization_id());
        """
    )
    op.execute(
        """
        CREATE POLICY notifications_update_own_org ON notifications
        FOR UPDATE USING (
            organization_id = get_user_organization_id()
            AND (user_id IS NULL OR user_id = auth.uid())
        )
        WITH CHECK (organization_id = get_user_organization_id());
        """
    )

    op.execute("GRANT SELECT, INSERT, UPDATE ON notifications TO canopyai_app;")

    op.alter_column('audit_log', 'actor',
               existing_type=sa.VARCHAR(length=255),
               comment='Who/what caused this event, e.g. "CanoryAI", "System", or a user identifier.',
               existing_comment='Who/what caused this event, e.g. "CanopyAI", "System", or a user identifier.',
               existing_nullable=False)
    op.create_table_comment(
        'organizations',
        "Tenant/company records. Root of CanoryAI's multi-tenant data isolation.",
        existing_comment="Tenant/company records. Root of CanopyAI's multi-tenant data isolation.",
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS notifications_select_own_org ON notifications;")
    op.execute("DROP POLICY IF EXISTS notifications_insert_own_org ON notifications;")
    op.execute("DROP POLICY IF EXISTS notifications_update_own_org ON notifications;")
    op.execute("ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'organizations',
        "Tenant/company records. Root of CanopyAI's multi-tenant data isolation.",
        existing_comment="Tenant/company records. Root of CanoryAI's multi-tenant data isolation.",
        schema=None
    )
    op.alter_column('audit_log', 'actor',
               existing_type=sa.VARCHAR(length=255),
               comment='Who/what caused this event, e.g. "CanopyAI", "System", or a user identifier.',
               existing_comment='Who/what caused this event, e.g. "CanoryAI", "System", or a user identifier.',
               existing_nullable=False)
    op.drop_index('ix_notifications_recipient_unread', table_name='notifications')
    op.drop_index('ix_notifications_organization_id', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
