"""add notification preferences table

Revision ID: 766979685e12
Revises: 85c59a7220da
Create Date: 2026-07-10 16:22:52.182004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766979685e12'
down_revision: Union[str, Sequence[str], None] = '85c59a7220da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email_on_shipment_completed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_on_team_member_added', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_on_team_member_removed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_on_plan_changed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id'),
    comment='One row per organization. Controls whether each event type ALSO sends an email (via Resend) on top of the in-app notification, which always fires regardless of these settings.'
    )

    op.execute("ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE notification_preferences FORCE ROW LEVEL SECURITY;")

    # Owner/admin-only write enforcement happens at the route level (see
    # app/api/v1/organizations.py's update_notification_preferences) —
    # matching how plan updates work, where RLS scopes to "your own org"
    # and the application layer checks the caller's specific role within
    # it. RLS alone can't express "role = owner or admin" without a
    # second lookup anyway, so there's no isolation benefit to
    # duplicating that check here; every member can read, only
    # owner/admin can actually reach the update route.
    op.execute(
        """
        CREATE POLICY notification_preferences_own_org ON notification_preferences
        FOR ALL USING (organization_id = get_user_organization_id())
        WITH CHECK (organization_id = get_user_organization_id());
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE ON notification_preferences TO canopyai_app;")
    # service_role also needs a direct grant here, not just canopyai_app —
    # BYPASSRLS (which service_role has) only bypasses ROW policies, not
    # the base table-level GRANT system. The SECURITY DEFINER functions
    # added in the next migration execute as service_role and need this
    # to actually read the table, regardless of RLS.
    op.execute("GRANT SELECT ON notification_preferences TO service_role;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS notification_preferences_own_org ON notification_preferences;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
