"""add organization sso columns

Revision ID: ee25a5939227
Revises: 690ce11f4fef
Create Date: 2026-07-10 07:50:47.343316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee25a5939227'
down_revision: Union[str, Sequence[str], None] = '690ce11f4fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('sso_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('sso_domain', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('sso_provider_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['sso_domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'sso_provider_id')
    op.drop_column('organizations', 'sso_domain')
    op.drop_column('organizations', 'sso_enabled')
    # ### end Alembic commands ###
